config/routes.rb
Rails.application.routes.draw do
  resources :boards
  root 'boards#index'

  # sign in
  # 로그인 페이지
  get '/signin' => 'sessions#signin', as: :user_signin
  # 실제 로그인
  post '/signin' => 'sessions#user_signin'


  # sign up
  # 회원가입 페이지
  get '/signup' => 'sessions#signup', as: :user_signup
  # 실제 회원가입
  post '/signup' => 'sessions#user_signup'

  # sign out
  # 로그아웃
  delete '/signout' => 'sessions#signout', as: :user_signout

end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :board

  def require_permission?(user)
    self.user.id == user.id
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :board
end

app/models/user.rb
class User < ActiveRecord::Base
  # 암호화된 비번을 가지고 있습니다.
  # 이것을 통해서 password_digest에 저장할 수 있음.
  has_secure_password
  has_many :likes
  has_many :comments
  has_many :boards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :user_signed_in?

  def current_user
    # 현재 접속한 유저
    # current_user가 비어 있다면 뒤를 실행하고 비어있지 않다면 그대로 진행한다.
    # @current_user ||= User.find(session[:user_id])
    if !session[:user_id].nil?
      @current_user = User.find(session[:user_id])
    end
    @current_user
  end

  # ?로 정의 되어 있으면 Boolean으로 return된다.
  def user_signed_in?
    # 유저가 로그인 했는지 여부(boolean)
    # session[:user_id] 비어있으면 >> 로그인 안한거 >> false
    # session[:user_id] 채워져있으면 >> 로그인 한거 >> true
    !session[:user_id].nil?
  end

  # !(bang) 내용물을 변화시킬수 있는 메소드에 붙여줌
  # element.upacse! => element 자체가 변화함
  # element2 = element.upcase => return 값이 변화함
  def authenticate_user!
    #유저가 로그인 했다면 진행
    #유저가 로그인 하지 않았다면 로그인 페이지로
    if session[:user_id].nil?
      redirect_to '/signin', notice: '로그인이 필요합니다.'
    end
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = current_user.boards.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show
    @like = Like.where(
      user_id: current_user.id,
      board_id: params[:id]
    )
  end

  def like_board
    like = Like.where(
      user_id: current_user.id,
      board_id: params[:board_id]
    )

    if like.length > 0
      #만약에 좋아요를 이미 누른 상태라면
      like.first.destroy
      puts '좋아요 취소'
    else
      #만약에 처음 좋아요를 누른 상태라면
      like = Like.create(
        user_id: current_user.id,
        board_id: params[:board_id]
      )
      puts '좋아요 누름'
    end
    redirect_to :back
  end

  def dislike_board
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:title, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # 회원가입 페이지
  def signup

  end

  #실제 회원가입이 이루어지는 곳
  def user_signup
    user = User.new(email: params[:email],
                    password: params[:password],
                    password_confirmation: params[:password_confirmation])

    #
    if user.save
      puts "done"
      redirect_to '/signin', notice: "회원가입이 완료!"
    else
      puts "error"
      redirect_to '/signup', notice: "잘못된 비밀번호 입니다."
    end
  end

  # 로그인 페이지
  def signin

  end

  # 로그인이 실제로 이루어지는 곳
  def user_signin
    user = User.find_by(email: params[:email])

    # user가 존재하고, parameter로 넘어온 비밀번호가 일치하다면
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/', notice: "로그인에 성공했습니다."
    else
      redirect_to '/signin', notice: "이메일이 없거나, 비밀번호가 틀렸습니다."
    end
  end

  #로그아웃
  def signout
    # session.out과 동일한 역할 user_id만 session에서 날려준다.
    session.delete(:user_id)
    redirect_to '/', notice: "로그아웃 성공!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: 'form-control'%>
  </div>
  <div class="actions">
    <%= f.submit '작성하기', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form' %>

<%= link_to '글보기', @board, class: 'btn btn-primary' %> |
<%= link_to '홈으로', boards_path, class: 'btn btn-dark'  %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Boards</h1>

<table class="table table-hover text-center">
  <thead>
    <tr>
      <th width="15%">글번호</th>
      <th width="60%">제목</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr class="board" data-id="<%= board.id%>">
        <td><%= board.id %></td>
        <td class="title"><%= board.title %></td>
        <!-- <td><%= link_to '보기', board, class: 'btn btn-primary'%></td> -->
        <!-- <td><%= link_to '수정', edit_board_path(board), class: 'btn btn-success' %></td> -->
        <!-- <td><%= link_to '삭제', board, class: 'btn btn-danger',method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to '새글쓰기', new_board_path, class: 'btn btn-dark' %>

 <!-- 버튼을 누르면 prompt창이 떠서 입력메시지를 입력할 수 있고,
 해당 내용으로 모든 제목을 바꿔버립니다. -->
<a class='btn btn-warning' id='change-title'>제목 바꾸기</a>
<a class='btn btn-danger color-btn' haha="text-danger">빨강</a>
<a class='btn btn-primary color-btn' haha="text-primary">파랑</a>
<a class='btn btn-warning color-btn' haha="text-warning">노랑</a>
<% content_for :script do %>
  <script>
  </script>

  <script src="/change_title.js"></script>
  <script src="/change_color.js"></script>
  <script src="/change_page.js"></script>

<% end %>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form' %>

<%= link_to '홈으로', boards_path, class: 'btn btn-dark' %>

app/views/boards/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @board.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @board.content %>
</p>

<!-- 유저 권한을 검사하여 글쓴이 자기 자신이라면 삭제와 수정 버튼을 보여줌 -->
<% if user_signed_in? && @board.require_permission?(current_user)%>
  <%= link_to '<i class="fas fa-trash"></i> 삭제'.html_safe, @board, class: 'btn btn-danger', data: {method: :delete, confirm: 'Are you sure?' } %> |
  <%= link_to '<i class="fas fa-pencil-alt"></i> 수정'.html_safe, edit_board_path(@board), class: 'btn btn-primary' %> |
<% end %>
<% if @like.length > 0 %> <!-- 눌려있을 때 -->
  <button type="button" class="btn btn-primary like"><i class="far fa-thumbs-up"></i>좋아요(<span id="like-count"><%= @board.likes.count %></span>)</button></a> |
<%else%> <!-- 처음 누를때 -->
  <button type="button" class="btn btn-outline-primary like"><i class="far fa-thumbs-up"></i>좋아요(<span id="like-count"><%= @board.likes.length %></span>)</button></a> |
<%end%>
<%= link_to '<i class="fas fa-home"></i> 홈으로'.html_safe, boards_path, class: 'btn btn-dark'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JsClass</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Board</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">User</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <% if user_signed_in?%>
          <a class="dropdown-item"><%= current_user.email %></a>
          <%= link_to 'Sign out', user_signout_path, class: 'dropdown-item', data: {method: :delete, confirm: "로그아웃 하시겠습니까?"} %>
          <% else %>
          <!-- <a class="dropdown-item" href="#">Sign in</a> -->
          <%= link_to 'Sign in', user_signin_path, class: 'dropdown-item'%>
          <!-- <a class="dropdown-item" href="#">Sign up</a> -->
          <%= link_to 'Sign up', user_signup_path, class: 'dropdown-item'%>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>
<!-- 적용한 bootstrap -->
<div class="container" style="margin-top: 5rem !important;">
  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
      <%= flash[:notice] %>
    </div>
  <% end %>
<%= yield %>
</div>
  <!-- content_for :script 를 찾는다. -->
  <%= yield :script%>
  <script defer src="https://use.fontawesome.com/releases/v5.0.2/js/all.js"></script>
</body>
</html>